#
# Copyright (c) 2017-2023 Fernando Pelliccioni
#

branches:
  only:
  - master
  - dev

linux: &linux
   os: linux
   sudo: required
   language: python
  #  python: "3.6"
   services:
     - docker

osx: &osx
   os: osx
   sudo: required
   # language: python
   # python: "3.6"
   language: generic


matrix:
   include:
      - <<: *osx
        osx_image: xcode12
        env: CONAN_APPLE_CLANG_VERSIONS=12.0 TRAVIS_PYTHON_VERSION=3.8 PYTHON_FULL_VERSION=3.8.2
        python: "3.8"

      # - <<: *osx
      #   osx_image: xcode11.4
      #   env: CONAN_APPLE_CLANG_VERSIONS=11.0 TRAVIS_PYTHON_VERSION=3.6 PYTHON_FULL_VERSION=3.6.2
      #   python: "3.6"

      # - <<: *osx
      #   osx_image: xcode10.1
      #   env: CONAN_APPLE_CLANG_VERSIONS=10.0 TRAVIS_PYTHON_VERSION=3.6 PYTHON_FULL_VERSION=3.6.2
      #   python: "3.6"

      # - <<: *osx
      #   osx_image: xcode9
      #   env: CONAN_APPLE_CLANG_VERSIONS=9.0 TRAVIS_PYTHON_VERSION=3.6 PYTHON_FULL_VERSION=3.6.2
      #   python: "3.6"

# ---------------------------------------------------------------------------


      - <<: *linux
        env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6
        compiler: gcc
        python: "2.7"

      - <<: *linux
        env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6
        compiler: gcc
        python: "3.6"

      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3  TRAVIS_PYTHON_VERSION=2.7 PYTHON_FULL_VERSION=2.7.13
        python: "2.7"

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 TRAVIS_PYTHON_VERSION=2.7 PYTHON_FULL_VERSION=2.7.13
        python: "2.7"

      # - <<: *osx
      #   osx_image: xcode7.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=7.3 TRAVIS_PYTHON_VERSION=3.4 PYTHON_FULL_VERSION=3.4.2
      #   # PYTHON_FULL_VERSION=3.4.7
      #   python: "3.4"

      # - <<: *osx
      #   osx_image: xcode8.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=8.1 TRAVIS_PYTHON_VERSION=3.4 PYTHON_FULL_VERSION=3.4.2
      #   python: "3.4"

      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3 TRAVIS_PYTHON_VERSION=3.5 PYTHON_FULL_VERSION=3.5.2
        # PYTHON_FULL_VERSION=3.5.4
        python: "3.5"

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 TRAVIS_PYTHON_VERSION=3.5 PYTHON_FULL_VERSION=3.5.2
        python: "3.5"

      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3 TRAVIS_PYTHON_VERSION=3.6 PYTHON_FULL_VERSION=3.6.2
        python: "3.6"

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 TRAVIS_PYTHON_VERSION=3.6 PYTHON_FULL_VERSION=3.6.2
        python: "3.6"

install:

  - set -e
  # - set -x

  - |
    if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
      brew update || brew update
      brew outdated pyenv || brew upgrade pyenv
      brew install pyenv-virtualenv
      brew install cmake || true

      if which pyenv > /dev/null; then
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
      fi

      pyenv install --list
      pyenv install $PYTHON_FULL_VERSION
      pyenv virtualenv $PYTHON_FULL_VERSION conan

      pyenv rehash
      pyenv activate conan
    fi

  # - pip install conan_package_tools --upgrade
  # - pip install conan --upgrade
  - pip install wheel --upgrade
  - pip install twine --upgrade
  # - conan user


script:

  - set -e
  # - set -x

  - |
    if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
      if which pyenv > /dev/null; then
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
      fi
      pyenv activate conan
    fi

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      chmod a+x .travis/entrypoint.sh
      /usr/bin/docker run --rm -ti -e TRAVIS_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION -v ${TRAVIS_BUILD_DIR}:/home/conan/project -v ${TRAVIS_BUILD_DIR}/.travis/entrypoint.sh:/tmp/entrypoint.sh lasote/conangcc63 /bin/bash -c /tmp/entrypoint.sh
    else
      python --version
      pip install  -e .
      python setup.py sdist
      python setup.py bdist_wheel
    fi

  # - python setup.py sdist

  # TestPyPI ... https://packaging.python.org/guides/using-testpypi/
  - |
    if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      twine upload -u ${PYPI_USER_NAME} -p ${PYPI_PASSWORD} dist/* || true
    else
      # For Testing Release
      # twine upload -r test -u ${PYPI_USER_NAME} -p ${PYPI_PASSWORD} dist/* || true
      twine upload -u ${PYPI_USER_NAME} -p ${PYPI_PASSWORD} --repository-url https://test.pypi.org/legacy/ dist/*  || true
    fi



notifications:
  email:
    - fpelliccioni@gmail.com
  # slack: bitprim:CGkcy3Bjx7UUIxu9FSZTpaxE
  # webhooks:
  #   urls: https://webhooks.gitter.im/e/a19dd2b03bf676d2b622
  #   on_success: change
  #   on_failure: always
